const list = [
  {
    id: 1,
    title: 'ქირავდება 1 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'თბილისი',
    locationId: 1,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/1',
  },
  {
    id: 2,
    title: 'ქირავდება 2 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'თბილისი',
    locationId: 1,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/2',
  },
  {
    id: 3,
    title: 'ქირავდება 3 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'თბილისი',
    locationId: 1,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/3',
  },
  {
    id: 4,
    title: 'ქირავდება 3 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'ცხინვალი',
    locationId: 2,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/4',
  },
  {
    id: 5,
    title: 'ქირავდება 3 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'ცხინვალი',
    locationId: 2,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/5',
  },
  {
    id: 6,
    title: 'ქირავდება 3 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'ცხინვალი',
    locationId: 2,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/6',
  },
  {
    id: 7,
    title: 'ქირავდება 3 ოთახიანი  ბინა',
    price: 2564,
    floor: 5,
    sqm: 100,
    rooms: 2,
    location: 'ცხინვალი',
    locationId: 2,
    images: ['/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png', '/images/static/flat.png'],
    slug: '/flats/7',
  },
];
export default list;
